--- 
version: "2"
networks: 
  default: 
    driver: bridge
services: 
version: "2"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes: 
      - "/mnt/storage/appdata/organizr:/config"
      - "/mnt/storage/appdata/shared:/shared"
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - /mnt/storage/media/download-reprocess:/download-reprocess
      - /mnt/storage/appdata/plex:/config
      - /mnt/storage/media/tv:/data/tvshows
      - /mnt/storage/media/homemovies:/data/homemovies
      - /mnt/storage/media/photos:/data/photos
      - /mnt/storage/media/exercisevideos:/data/exercisevideos
      - /mnt/storage/media/movies:/data/movies
      - /mnt/storage/media/TEMP_POSTPROCESSING:/transcode
    environment:
      - VERSION=public
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
      - PLEX_CLAIM=${PLEX_CLAIM_CODE}
    network_mode: host
    restart: always
    volumes: 
      - "/mnt/storage/appdata/plex:/config"
      - "/mnt/storage/media/TEMP_POSTPROCESSING:/transcode"
      - "/mnt/storage/media/tv:/data/tvshows"
      - "/mnt/storage/media/homemovies:/data/homemovies"
      - "/mnt/storage/media/photos:/data/photos"
      - "/mnt/storage/media/exercisevideos:/data/exercisevideos"
      - "/mnt/storage/media/movies:/data/movies"
      - "/mnt/storage/appdata/shared:/shared"
    ports:
      - 32400:32400/tcp
  portainer: 
    container_name: portainer
    image: portainer/portainer:latest
    ports:
      - 9000:9000
    restart: always
    volumes: 
      - "/mnt/storage/appdata/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
  radarr: 
    container_name: radarr
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
    image: linuxserver/radarr:latest
    ports:
      - 7878:7878 
    restart: always
    volumes: 
      - "/mnt/storage/appdata/radarr:/config"
      - "/mnt/storage/media/movies:/movies"
      - "/mnt/storage/media/downloads:/downloads"
      - "/mnt/storage/appdata/shared:/shared"
  sabnzbd: 
    container_name: sabnzbd
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - TZ=America/Chicago
    image: linuxserver/sabnzbd:latest
    ports:
      - 8080:8080
    restart: always
    volumes: 
      - "/mnt/storage/appdata/sabnzbd/config:/config"
      - "/mnt/storage/media/incomplete-downloads:/incomplete-downloads"
      - "/mnt/storage/media/downloads:/downloads"
      - "/mnt/storage/appdata/shared:/shared"
  sonarr: 
    container_name: sonarr
    depends_on: 
      - sabnzbd
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
    image: linuxserver/sonarr:preview
    links: 
      - sabnzbd
    ports:
      - 8989:8989
    restart: always
    volumes: 
      - "/mnt/storage/appdata/sonarr:/config"
      - "/mnt/storage/media/tv_import:/tv_import"
      - "/mnt/storage/media/tv:/tv"
      - "/mnt/storage/media/downloads:/downloads"
      - "/mnt/storage/appdata/shared:/shared"
